// Comprehensive emoji dataset for the Discord-style picker.
//
// Each entry is a [emoji, keywords] tuple. Keywords are space-separated and
// lowercase; English terms cover the full set, with Russian aliases added for
// common emoji so search works in both languages. Category labels are Russian.
//
// Only base emoji are listed (no skin-tone variants) — the picker offers them
// as-is. The backend (schemas/chats.py::EMOJI_PATTERN) accepts every emoji here
// as a reaction, including ZWJ sequences, flags and keycaps.

export type EmojiEntry = readonly [emoji: string, keywords: string];

export type EmojiCategoryId =
  | "recent"
  | "smileys"
  | "people"
  | "animals"
  | "food"
  | "activities"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export type EmojiCategory = {
  id: EmojiCategoryId;
  label: string;
  icon: string;
  entries: readonly EmojiEntry[];
};

const SMILEYS: readonly EmojiEntry[] = [
  ["😀", "grinning face smile happy улыбка радость"],
  ["😃", "grinning big eyes happy smile улыбка"],
  ["😄", "grinning smiling eyes happy joy смех радость"],
  ["😁", "beaming grin smile happy улыбка"],
  ["😆", "grinning squinting laugh haha смех"],
  ["😅", "grinning sweat relief phew смех пот"],
  ["🤣", "rolling floor laughing rofl смех угар"],
  ["😂", "joy tears laughing lol смех слёзы"],
  ["🙂", "slight smile улыбка"],
  ["🙃", "upside down silly ирония"],
  ["🫠", "melting face hot melt тает"],
  ["😉", "wink flirt подмигивание"],
  ["😊", "smiling blush happy улыбка милый"],
  ["😇", "innocent halo angel ангел"],
  ["🥰", "smiling hearts love adore любовь сердечки"],
  ["😍", "heart eyes love crush любовь восторг"],
  ["🤩", "star struck amazed wow восторг звёзды"],
  ["😘", "blowing kiss love поцелуй"],
  ["😗", "kissing поцелуй"],
  ["☺️", "smiling relaxed happy улыбка"],
  ["😚", "kissing closed eyes поцелуй"],
  ["😙", "kissing smiling поцелуй"],
  ["🥲", "smiling tear happy sad слёзы радость"],
  ["😋", "yum savoring delicious вкусно язык"],
  ["😛", "tongue out playful язык"],
  ["😜", "winking tongue joke язык шутка"],
  ["🤪", "zany goofy crazy дурачусь"],
  ["😝", "squinting tongue язык"],
  ["🤑", "money mouth rich деньги"],
  ["🤗", "hug hugging обнимаю объятия"],
  ["🤭", "hand over mouth giggle ой хихи"],
  ["🫢", "open eyes hand mouth shock ой"],
  ["🤫", "shushing quiet тихо тсс"],
  ["🤔", "thinking hmm думаю размышление"],
  ["🫡", "saluting respect честь салют"],
  ["🤐", "zipper mouth secret молчу"],
  ["🤨", "raised eyebrow skeptic недоверие"],
  ["😐", "neutral face meh нейтрально"],
  ["😑", "expressionless без эмоций"],
  ["😶", "no mouth speechless молчание"],
  ["🫥", "dotted line face invisible исчезаю"],
  ["😏", "smirk sly хитрость ухмылка"],
  ["😒", "unamused meh недовольство"],
  ["🙄", "rolling eyes annoyed закатываю глаза"],
  ["😬", "grimacing awkward неловко"],
  ["🤥", "lying pinocchio вру ложь"],
  ["😌", "relieved calm спокойствие облегчение"],
  ["😔", "pensive sad грусть"],
  ["😪", "sleepy tired сон усталость"],
  ["🤤", "drooling слюни"],
  ["😴", "sleeping zzz сон спать"],
  ["😷", "mask sick медицинская маска болезнь"],
  ["🤒", "thermometer sick fever болезнь температура"],
  ["🤕", "head bandage hurt травма"],
  ["🤢", "nauseated sick тошнота"],
  ["🤮", "vomiting sick рвота"],
  ["🤧", "sneezing sick чихаю"],
  ["🥵", "hot face heat жарко"],
  ["🥶", "cold face freezing холодно"],
  ["🥴", "woozy dizzy drunk пьяный"],
  ["😵", "dizzy face крестики голова"],
  ["😵‍💫", "spiral eyes confused голова кружится"],
  ["🤯", "exploding head mind blown взрыв мозга"],
  ["🤠", "cowboy ковбой"],
  ["🥳", "partying hat celebrate праздник вечеринка"],
  ["🥸", "disguised glasses маскировка"],
  ["😎", "sunglasses cool крутой очки"],
  ["🤓", "nerd glasses ботаник"],
  ["🧐", "monocle inspect монокль"],
  ["😕", "confused растерянность"],
  ["🫤", "diagonal mouth meh неопределённость"],
  ["😟", "worried беспокойство"],
  ["🙁", "slight frown грусть"],
  ["☹️", "frowning грусть"],
  ["😮", "open mouth surprise удивление"],
  ["😯", "hushed surprise удивление"],
  ["😲", "astonished shock шок"],
  ["😳", "flushed embarrassed смущение"],
  ["🥺", "pleading puppy eyes умоляю жалость"],
  ["🥹", "holding back tears слёзы трогательно"],
  ["😦", "frowning open mouth"],
  ["😧", "anguished страдание"],
  ["😨", "fearful scared страх"],
  ["😰", "anxious sweat тревога"],
  ["😥", "sad relieved sweat грусть"],
  ["😢", "crying tear плач слеза"],
  ["😭", "loudly crying sob рыдаю плач"],
  ["😱", "screaming fear крик ужас"],
  ["😖", "confounded досада"],
  ["😣", "persevering усилие"],
  ["😞", "disappointed разочарование"],
  ["😓", "downcast sweat пот грусть"],
  ["😩", "weary tired усталость"],
  ["😫", "tired устал"],
  ["🥱", "yawning bored зеваю скука"],
  ["😤", "huffing triumph пар недовольство"],
  ["😡", "pouting angry red злость гнев"],
  ["😠", "angry mad злость"],
  ["🤬", "swearing cursing мат ругань"],
  ["😈", "smiling horns devil чёрт дьявол"],
  ["👿", "imp angry horns чёрт"],
  ["💀", "skull dead череп смерть"],
  ["☠️", "skull crossbones poison череп яд"],
  ["💩", "poop pile funny какашка"],
  ["🤡", "clown клоун"],
  ["👹", "ogre demon огр демон"],
  ["👺", "goblin гоблин"],
  ["👻", "ghost boo призрак привидение"],
  ["👽", "alien инопланетянин"],
  ["👾", "alien monster space invader монстр"],
  ["🤖", "robot робот"],
  ["😺", "smiling cat кот улыбка"],
  ["😸", "grinning cat кот"],
  ["😹", "cat tears joy кот смех"],
  ["😻", "cat heart eyes кот любовь"],
  ["😼", "cat wry smile кот ухмылка"],
  ["😽", "kissing cat кот поцелуй"],
  ["🙀", "weary cat shock кот ужас"],
  ["😿", "crying cat кот плач"],
  ["😾", "pouting cat кот злость"],
  ["💋", "kiss mark lips поцелуй губы"],
  ["💌", "love letter письмо любовь"],
  ["💘", "heart arrow cupid сердце стрела"],
  ["💝", "heart ribbon gift сердце подарок"],
  ["💖", "sparkling heart сердце блеск"],
  ["💗", "growing heart сердце"],
  ["💓", "beating heart сердце пульс"],
  ["💞", "revolving hearts сердца"],
  ["💕", "two hearts сердечки"],
  ["💟", "heart decoration сердце"],
  ["❣️", "heart exclamation сердце"],
  ["💔", "broken heart разбитое сердце"],
  ["❤️‍🔥", "heart on fire passion страсть сердце огонь"],
  ["❤️‍🩹", "mending heart healing сердце лечится"],
  ["❤️", "red heart love любовь сердце красное"],
  ["🩷", "pink heart розовое сердце"],
  ["🧡", "orange heart оранжевое сердце"],
  ["💛", "yellow heart жёлтое сердце"],
  ["💚", "green heart зелёное сердце"],
  ["💙", "blue heart синее сердце"],
  ["🩵", "light blue heart голубое сердце"],
  ["💜", "purple heart фиолетовое сердце"],
  ["🤎", "brown heart коричневое сердце"],
  ["🖤", "black heart чёрное сердце"],
  ["🩶", "grey heart серое сердце"],
  ["🤍", "white heart белое сердце"],
  ["💯", "hundred points perfect сто перфект"],
  ["💢", "anger symbol злость вена"],
  ["💥", "collision boom взрыв бум"],
  ["💫", "dizzy stars звёзды кружится"],
  ["💦", "sweat droplets water брызги пот"],
  ["💨", "dash wind smoke пар ветер"],
  ["🕳️", "hole дыра"],
  ["💬", "speech balloon chat реплика чат"],
  ["💭", "thought balloon мысль"],
  ["💤", "zzz sleep сон"],
];

const PEOPLE: readonly EmojiEntry[] = [
  ["👋", "waving hand hello bye привет пока"],
  ["🤚", "raised back hand рука"],
  ["🖐️", "hand fingers splayed ладонь"],
  ["✋", "raised hand stop стоп ладонь"],
  ["🖖", "vulcan salute spock"],
  ["🫱", "rightwards hand рука вправо"],
  ["🫲", "leftwards hand рука влево"],
  ["🫳", "palm down hand ладонь вниз"],
  ["🫴", "palm up hand ладонь вверх"],
  ["🫷", "leftwards pushing hand стоп"],
  ["🫸", "rightwards pushing hand стоп"],
  ["👌", "ok hand окей"],
  ["🤌", "pinched fingers итальянский жест"],
  ["🤏", "pinching hand little чуть-чуть"],
  ["✌️", "victory peace мир победа"],
  ["🤞", "crossed fingers luck удача"],
  ["🫰", "hand heart fingers сердце пальцами"],
  ["🤟", "love you gesture люблю"],
  ["🤘", "rock horns рок"],
  ["🤙", "call me shaka позвони"],
  ["👈", "point left влево"],
  ["👉", "point right вправо"],
  ["👆", "point up вверх"],
  ["🖕", "middle finger fuck средний палец"],
  ["👇", "point down вниз"],
  ["☝️", "index up вверх"],
  ["🫵", "point viewer ты"],
  ["👍", "thumbs up like yes лайк класс да"],
  ["👎", "thumbs down dislike no дизлайк нет"],
  ["✊", "raised fist кулак"],
  ["👊", "fist bump punch кулак удар"],
  ["🤛", "left fist кулак"],
  ["🤜", "right fist кулак"],
  ["👏", "clapping applause аплодисменты браво"],
  ["🙌", "raising hands praise ура руки вверх"],
  ["🫶", "heart hands love сердце руками любовь"],
  ["👐", "open hands открытые ладони"],
  ["🤲", "palms up together мольба"],
  ["🤝", "handshake deal рукопожатие сделка"],
  ["🙏", "folded hands pray thanks молитва спасибо пожалуйста"],
  ["✍️", "writing hand пишу"],
  ["💅", "nail polish маникюр"],
  ["🤳", "selfie селфи"],
  ["💪", "flexed biceps strong сила мышцы"],
  ["🦾", "mechanical arm протез рука"],
  ["🦿", "mechanical leg протез нога"],
  ["🦵", "leg нога"],
  ["🦶", "foot ступня"],
  ["👂", "ear ухо"],
  ["🦻", "ear hearing aid слух"],
  ["👃", "nose нос"],
  ["🧠", "brain мозг"],
  ["🫀", "anatomical heart сердце орган"],
  ["🫁", "lungs лёгкие"],
  ["🦷", "tooth зуб"],
  ["🦴", "bone кость"],
  ["👀", "eyes look watch глаза смотрю"],
  ["👁️", "eye глаз"],
  ["👅", "tongue язык"],
  ["👄", "mouth lips губы рот"],
  ["🫦", "biting lip губа"],
  ["👶", "baby младенец"],
  ["🧒", "child ребёнок"],
  ["👦", "boy мальчик"],
  ["👧", "girl девочка"],
  ["🧑", "person человек"],
  ["👱", "blond hair блондин"],
  ["👨", "man мужчина"],
  ["🧔", "bearded борода"],
  ["👩", "woman женщина"],
  ["🧓", "older person пожилой"],
  ["👴", "old man дед"],
  ["👵", "old woman бабушка"],
  ["🙍", "person frowning хмурый"],
  ["🙎", "person pouting надутый"],
  ["🙅", "no gesture нельзя нет"],
  ["🙆", "ok gesture окей да"],
  ["💁", "tipping hand info секретарь"],
  ["🙋", "raising hand вопрос рука"],
  ["🧏", "deaf person глухой"],
  ["🙇", "bowing поклон"],
  ["🤦", "facepalm рукалицо фейспалм"],
  ["🤷", "shrug не знаю плечи"],
  ["🧑‍⚕️", "health worker doctor врач"],
  ["🧑‍🎓", "student студент"],
  ["🧑‍🏫", "teacher учитель"],
  ["🧑‍🌾", "farmer фермер"],
  ["🧑‍🍳", "cook chef повар"],
  ["🧑‍🔧", "mechanic механик"],
  ["🧑‍🏭", "factory worker рабочий"],
  ["🧑‍💼", "office worker офис"],
  ["🧑‍🔬", "scientist учёный"],
  ["🧑‍💻", "technologist programmer программист айти"],
  ["🧑‍🎤", "singer певец"],
  ["🧑‍🎨", "artist художник"],
  ["🧑‍✈️", "pilot пилот"],
  ["🧑‍🚀", "astronaut космонавт"],
  ["🧑‍🚒", "firefighter пожарный"],
  ["👮", "police полиция полицейский"],
  ["🕵️", "detective детектив шпион"],
  ["💂", "guard охрана"],
  ["🥷", "ninja ниндзя"],
  ["👷", "construction worker строитель"],
  ["🫅", "person crown корона"],
  ["🤴", "prince принц"],
  ["👸", "princess принцесса"],
  ["👳", "turban тюрбан"],
  ["👲", "skullcap"],
  ["🧕", "headscarf хиджаб"],
  ["🤵", "tuxedo смокинг жених"],
  ["👰", "veil bride невеста"],
  ["🤰", "pregnant беременная"],
  ["🤱", "breastfeeding кормление"],
  ["👼", "baby angel ангел"],
  ["🎅", "santa дед мороз санта"],
  ["🤶", "mrs claus"],
  ["🦸", "superhero супергерой"],
  ["🦹", "supervillain суперзлодей"],
  ["🧙", "mage wizard маг волшебник"],
  ["🧚", "fairy фея"],
  ["🧛", "vampire вампир"],
  ["🧜", "merperson русалка"],
  ["🧝", "elf эльф"],
  ["🧞", "genie джинн"],
  ["🧟", "zombie зомби"],
  ["🧌", "troll тролль"],
  ["💆", "massage массаж"],
  ["💇", "haircut стрижка"],
  ["🚶", "walking иду пешеход"],
  ["🧍", "standing стою"],
  ["🧎", "kneeling на коленях"],
  ["🏃", "running бегу бег"],
  ["💃", "dancing woman танец"],
  ["🕺", "dancing man танец"],
  ["👯", "bunny ears partying танцы"],
  ["🧖", "sauna баня сауна"],
  ["🧗", "climbing скалолаз"],
  ["🤺", "fencing фехтование"],
  ["🏇", "horse racing скачки"],
  ["⛷️", "skier лыжи"],
  ["🏂", "snowboarder сноуборд"],
  ["🏌️", "golfer гольф"],
  ["🏄", "surfing сёрфинг"],
  ["🚣", "rowing гребля"],
  ["🏊", "swimming плавание"],
  ["⛹️", "basketball player баскетбол"],
  ["🏋️", "weight lifting штанга качалка"],
  ["🚴", "biking велосипед"],
  ["🚵", "mountain biking велосипед"],
  ["🤸", "cartwheel колесо"],
  ["🤼", "wrestling борьба"],
  ["🤽", "water polo поло"],
  ["🤾", "handball гандбол"],
  ["🤹", "juggling жонглёр"],
  ["🧘", "meditation yoga йога медитация"],
  ["🛀", "bath ванна"],
  ["🛌", "sleeping bed сплю кровать"],
  ["👭", "two women holding hands подруги"],
  ["👫", "woman man holding hands пара"],
  ["👬", "two men holding hands друзья"],
  ["💏", "kiss couple поцелуй пара"],
  ["💑", "couple heart пара любовь"],
  ["👪", "family семья"],
  ["👨‍👩‍👧‍👦", "family parents children семья"],
  ["🗣️", "speaking head говорит"],
  ["👤", "silhouette профиль аноним"],
  ["👥", "busts people люди"],
  ["👣", "footprints следы"],
];

const ANIMALS: readonly EmojiEntry[] = [
  ["🐶", "dog puppy собака пёс"],
  ["🐱", "cat kitten кот кошка"],
  ["🐭", "mouse мышь"],
  ["🐹", "hamster хомяк"],
  ["🐰", "rabbit bunny кролик заяц"],
  ["🦊", "fox лиса"],
  ["🐻", "bear медведь"],
  ["🐼", "panda панда"],
  ["🐻‍❄️", "polar bear белый медведь"],
  ["🐨", "koala коала"],
  ["🐯", "tiger тигр"],
  ["🦁", "lion лев"],
  ["🐮", "cow корова"],
  ["🐷", "pig свинья"],
  ["🐽", "pig nose пятачок"],
  ["🐸", "frog лягушка"],
  ["🐵", "monkey обезьяна"],
  ["🙈", "see no evil monkey обезьяна"],
  ["🙉", "hear no evil monkey обезьяна"],
  ["🙊", "speak no evil monkey обезьяна"],
  ["🐒", "monkey обезьяна"],
  ["🐔", "chicken курица"],
  ["🐧", "penguin пингвин"],
  ["🐦", "bird птица"],
  ["🐤", "baby chick цыплёнок"],
  ["🐣", "hatching chick цыплёнок"],
  ["🐥", "front chick цыплёнок"],
  ["🦆", "duck утка"],
  ["🦅", "eagle орёл"],
  ["🦉", "owl сова"],
  ["🦇", "bat летучая мышь"],
  ["🐺", "wolf волк"],
  ["🐗", "boar кабан"],
  ["🐴", "horse face лошадь"],
  ["🦄", "unicorn единорог"],
  ["🐝", "bee пчела"],
  ["🪲", "beetle жук"],
  ["🐛", "bug caterpillar гусеница"],
  ["🦋", "butterfly бабочка"],
  ["🐌", "snail улитка"],
  ["🐞", "ladybug божья коровка"],
  ["🐜", "ant муравей"],
  ["🪰", "fly муха"],
  ["🪳", "cockroach таракан"],
  ["🦗", "cricket кузнечик"],
  ["🕷️", "spider паук"],
  ["🕸️", "spider web паутина"],
  ["🦂", "scorpion скорпион"],
  ["🐢", "turtle черепаха"],
  ["🐍", "snake змея"],
  ["🦎", "lizard ящерица"],
  ["🦖", "trex dinosaur динозавр"],
  ["🦕", "sauropod dinosaur динозавр"],
  ["🐙", "octopus осьминог"],
  ["🦑", "squid кальмар"],
  ["🦐", "shrimp креветка"],
  ["🦞", "lobster омар"],
  ["🦀", "crab краб"],
  ["🐡", "blowfish рыба фугу"],
  ["🐠", "tropical fish рыба"],
  ["🐟", "fish рыба"],
  ["🐬", "dolphin дельфин"],
  ["🐳", "whale кит"],
  ["🐋", "whale кит"],
  ["🦈", "shark акула"],
  ["🐊", "crocodile крокодил"],
  ["🐅", "tiger тигр"],
  ["🐆", "leopard леопард"],
  ["🦓", "zebra зебра"],
  ["🦍", "gorilla горилла"],
  ["🦧", "orangutan орангутан"],
  ["🐘", "elephant слон"],
  ["🦣", "mammoth мамонт"],
  ["🦛", "hippo бегемот"],
  ["🦏", "rhino носорог"],
  ["🐪", "camel верблюд"],
  ["🐫", "two hump camel верблюд"],
  ["🦒", "giraffe жираф"],
  ["🦘", "kangaroo кенгуру"],
  ["🦬", "bison бизон"],
  ["🐃", "water buffalo буйвол"],
  ["🐂", "ox бык"],
  ["🐄", "cow корова"],
  ["🐎", "horse лошадь конь"],
  ["🐖", "pig свинья"],
  ["🐏", "ram баран"],
  ["🐑", "sheep овца"],
  ["🦙", "llama лама"],
  ["🐐", "goat коза"],
  ["🦌", "deer олень"],
  ["🐕", "dog собака"],
  ["🐩", "poodle пудель"],
  ["🦮", "guide dog поводырь"],
  ["🐕‍🦺", "service dog собака"],
  ["🐈", "cat кот"],
  ["🐈‍⬛", "black cat чёрный кот"],
  ["🪶", "feather перо"],
  ["🐓", "rooster петух"],
  ["🦃", "turkey индейка"],
  ["🦤", "dodo додо"],
  ["🦚", "peacock павлин"],
  ["🦜", "parrot попугай"],
  ["🦢", "swan лебедь"],
  ["🦩", "flamingo фламинго"],
  ["🕊️", "dove peace голубь мир"],
  ["🐇", "rabbit кролик"],
  ["🦝", "raccoon енот"],
  ["🦨", "skunk скунс"],
  ["🦡", "badger барсук"],
  ["🦫", "beaver бобр"],
  ["🦦", "otter выдра"],
  ["🦥", "sloth ленивец"],
  ["🐁", "mouse мышь"],
  ["🐀", "rat крыса"],
  ["🐿️", "chipmunk бурундук белка"],
  ["🦔", "hedgehog ёж"],
  ["🐾", "paw prints лапки следы"],
  ["🐉", "dragon дракон"],
  ["🐲", "dragon face дракон"],
  ["🌵", "cactus кактус"],
  ["🎄", "christmas tree ёлка"],
  ["🌲", "evergreen tree ель"],
  ["🌳", "deciduous tree дерево"],
  ["🌴", "palm tree пальма"],
  ["🪵", "wood log бревно"],
  ["🌱", "seedling росток"],
  ["🌿", "herb трава зелень"],
  ["☘️", "shamrock клевер"],
  ["🍀", "four leaf clover клевер удача"],
  ["🎍", "bamboo бамбук"],
  ["🪴", "potted plant растение"],
  ["🎋", "tanabata tree"],
  ["🍃", "leaves листья ветер"],
  ["🍂", "fallen leaves листья осень"],
  ["🍁", "maple leaf клён лист"],
  ["🍄", "mushroom гриб"],
  ["🐚", "shell ракушка"],
  ["🪸", "coral коралл"],
  ["🪨", "rock камень"],
  ["🌾", "rice plant колос"],
  ["💐", "bouquet букет цветы"],
  ["🌷", "tulip тюльпан"],
  ["🌹", "rose роза"],
  ["🥀", "wilted flower увядший цветок"],
  ["🌺", "hibiscus гибискус"],
  ["🌸", "cherry blossom сакура цветок"],
  ["🌼", "blossom цветок"],
  ["🌻", "sunflower подсолнух"],
  ["🌞", "sun face солнце"],
  ["🌝", "full moon face луна"],
  ["🌚", "new moon face луна"],
  ["🌙", "crescent moon месяц луна"],
  ["⭐", "star звезда"],
  ["🌟", "glowing star звезда блеск"],
  ["✨", "sparkles блеск магия искры"],
  ["⚡", "lightning bolt молния"],
  ["☄️", "comet комета"],
  ["💥", "boom взрыв"],
  ["🔥", "fire flame огонь пламя жар"],
  ["🌪️", "tornado торнадо"],
  ["🌈", "rainbow радуга"],
  ["☀️", "sun солнце"],
  ["🌤️", "sun behind cloud солнце облако"],
  ["⛅", "sun cloud облачно"],
  ["☁️", "cloud облако"],
  ["🌧️", "rain дождь"],
  ["⛈️", "thunderstorm гроза"],
  ["🌩️", "lightning cloud гроза"],
  ["🌨️", "snow cloud снег"],
  ["❄️", "snowflake снежинка снег"],
  ["☃️", "snowman снеговик"],
  ["⛄", "snowman снеговик"],
  ["🌬️", "wind ветер"],
  ["💧", "droplet капля вода"],
  ["💦", "sweat droplets брызги"],
  ["☔", "umbrella rain зонт дождь"],
  ["🌊", "wave ocean волна море"],
  ["🌍", "globe europe africa земля планета"],
  ["🌎", "globe americas земля"],
  ["🌏", "globe asia земля"],
];

const FOOD: readonly EmojiEntry[] = [
  ["🍏", "green apple яблоко"],
  ["🍎", "red apple яблоко"],
  ["🍐", "pear груша"],
  ["🍊", "tangerine orange мандарин апельсин"],
  ["🍋", "lemon лимон"],
  ["🍌", "banana банан"],
  ["🍉", "watermelon арбуз"],
  ["🍇", "grapes виноград"],
  ["🍓", "strawberry клубника"],
  ["🫐", "blueberries черника"],
  ["🍈", "melon дыня"],
  ["🍒", "cherries вишня черешня"],
  ["🍑", "peach персик"],
  ["🥭", "mango манго"],
  ["🍍", "pineapple ананас"],
  ["🥥", "coconut кокос"],
  ["🥝", "kiwi киви"],
  ["🍅", "tomato помидор"],
  ["🍆", "eggplant баклажан"],
  ["🥑", "avocado авокадо"],
  ["🥦", "broccoli брокколи"],
  ["🥬", "leafy green салат"],
  ["🥒", "cucumber огурец"],
  ["🌶️", "hot pepper перец острый"],
  ["🫑", "bell pepper перец"],
  ["🌽", "corn кукуруза"],
  ["🥕", "carrot морковь"],
  ["🫒", "olive оливка"],
  ["🧄", "garlic чеснок"],
  ["🧅", "onion лук"],
  ["🥔", "potato картофель картошка"],
  ["🍠", "sweet potato батат"],
  ["🥐", "croissant круассан"],
  ["🥯", "bagel бейгл"],
  ["🍞", "bread хлеб"],
  ["🥖", "baguette багет"],
  ["🥨", "pretzel крендель"],
  ["🧀", "cheese сыр"],
  ["🥚", "egg яйцо"],
  ["🍳", "fried egg яичница"],
  ["🧈", "butter масло"],
  ["🥞", "pancakes блины оладьи"],
  ["🧇", "waffle вафля"],
  ["🥓", "bacon бекон"],
  ["🥩", "steak meat мясо стейк"],
  ["🍗", "poultry leg курица нога"],
  ["🍖", "meat bone мясо"],
  ["🦴", "bone кость"],
  ["🌭", "hot dog хот-дог"],
  ["🍔", "hamburger burger бургер гамбургер"],
  ["🍟", "fries картошка фри"],
  ["🍕", "pizza пицца"],
  ["🫓", "flatbread лепёшка"],
  ["🥪", "sandwich сэндвич"],
  ["🥙", "stuffed flatbread шаурма"],
  ["🧆", "falafel фалафель"],
  ["🌮", "taco тако"],
  ["🌯", "burrito буррито"],
  ["🫔", "tamale тамале"],
  ["🥗", "salad салат"],
  ["🥘", "paella shallow pan плов"],
  ["🫕", "fondue фондю"],
  ["🥫", "canned food консервы"],
  ["🍝", "spaghetti pasta паста макароны"],
  ["🍜", "ramen noodles лапша рамен"],
  ["🍲", "stew суп рагу"],
  ["🍛", "curry карри"],
  ["🍣", "sushi суши"],
  ["🍱", "bento бенто"],
  ["🥟", "dumpling пельмени"],
  ["🦪", "oyster устрица"],
  ["🍤", "fried shrimp креветка темпура"],
  ["🍙", "rice ball онигири"],
  ["🍚", "cooked rice рис"],
  ["🍘", "rice cracker"],
  ["🍥", "fish cake"],
  ["🥠", "fortune cookie печенье"],
  ["🥮", "moon cake"],
  ["🍢", "oden"],
  ["🍡", "dango"],
  ["🍧", "shaved ice мороженое"],
  ["🍨", "ice cream мороженое"],
  ["🍦", "soft ice cream мороженое"],
  ["🥧", "pie пирог"],
  ["🧁", "cupcake капкейк"],
  ["🍰", "shortcake cake торт пирожное"],
  ["🎂", "birthday cake торт"],
  ["🍮", "custard pudding пудинг"],
  ["🍭", "lollipop леденец"],
  ["🍬", "candy конфета"],
  ["🍫", "chocolate шоколад"],
  ["🍿", "popcorn попкорн"],
  ["🍩", "doughnut пончик"],
  ["🍪", "cookie печенье"],
  ["🌰", "chestnut каштан"],
  ["🥜", "peanuts арахис орехи"],
  ["🫘", "beans бобы"],
  ["🍯", "honey мёд"],
  ["🥛", "milk молоко"],
  ["🍼", "baby bottle бутылочка"],
  ["🫖", "teapot чайник"],
  ["☕", "coffee tea кофе чай"],
  ["🍵", "tea green чай"],
  ["🧃", "juice box сок"],
  ["🥤", "cup straw напиток газировка"],
  ["🧋", "bubble tea чай"],
  ["🍶", "sake саке"],
  ["🍺", "beer пиво"],
  ["🍻", "beers cheers пиво тост"],
  ["🥂", "clinking glasses champagne шампанское тост"],
  ["🍷", "wine вино"],
  ["🥃", "whiskey виски"],
  ["🍸", "cocktail коктейль"],
  ["🍹", "tropical drink коктейль"],
  ["🧉", "mate мате"],
  ["🍾", "champagne bottle шампанское"],
  ["🧊", "ice cube лёд"],
  ["🥄", "spoon ложка"],
  ["🍴", "fork knife вилка нож"],
  ["🍽️", "plate cutlery тарелка"],
  ["🥢", "chopsticks палочки"],
  ["🧂", "salt соль"],
];

const ACTIVITIES: readonly EmojiEntry[] = [
  ["⚽", "soccer football футбол мяч"],
  ["🏀", "basketball баскетбол"],
  ["🏈", "american football футбол"],
  ["⚾", "baseball бейсбол"],
  ["🥎", "softball софтбол"],
  ["🎾", "tennis теннис"],
  ["🏐", "volleyball волейбол"],
  ["🏉", "rugby регби"],
  ["🥏", "frisbee фрисби"],
  ["🎱", "8 ball pool бильярд"],
  ["🪀", "yo-yo йо-йо"],
  ["🏓", "ping pong настольный теннис"],
  ["🏸", "badminton бадминтон"],
  ["🏒", "hockey хоккей"],
  ["🏑", "field hockey хоккей"],
  ["🥍", "lacrosse лакросс"],
  ["🏏", "cricket крикет"],
  ["🪃", "boomerang бумеранг"],
  ["🥅", "goal net ворота"],
  ["⛳", "golf flag гольф"],
  ["🪁", "kite воздушный змей"],
  ["🏹", "bow arrow лук стрелы"],
  ["🎣", "fishing рыбалка"],
  ["🤿", "diving mask дайвинг"],
  ["🥊", "boxing glove бокс"],
  ["🥋", "martial arts кимоно"],
  ["🎽", "running shirt майка"],
  ["🛹", "skateboard скейт"],
  ["🛼", "roller skate ролики"],
  ["🛷", "sled санки"],
  ["⛸️", "ice skate коньки"],
  ["🥌", "curling кёрлинг"],
  ["🎿", "skis лыжи"],
  ["⛷️", "skier лыжник"],
  ["🏂", "snowboarder сноуборд"],
  ["🏋️", "weightlifting штанга"],
  ["🤼", "wrestling борьба"],
  ["🤸", "gymnastics гимнастика"],
  ["⛹️", "ball player мяч"],
  ["🤺", "fencing фехтование"],
  ["🤾", "handball гандбол"],
  ["🏌️", "golfing гольф"],
  ["🏇", "horse racing скачки"],
  ["🧘", "yoga йога"],
  ["🏄", "surfing сёрфинг"],
  ["🏊", "swimming плавание"],
  ["🤽", "water polo поло"],
  ["🚣", "rowing гребля"],
  ["🧗", "climbing скалолазание"],
  ["🚵", "mountain biking велоспорт"],
  ["🚴", "cycling велоспорт"],
  ["🏆", "trophy кубок награда победа"],
  ["🥇", "first place gold золото медаль"],
  ["🥈", "second place silver серебро медаль"],
  ["🥉", "third place bronze бронза медаль"],
  ["🏅", "sports medal медаль"],
  ["🎖️", "military medal медаль"],
  ["🏵️", "rosette розетка"],
  ["🎗️", "reminder ribbon лента"],
  ["🎫", "ticket билет"],
  ["🎟️", "admission tickets билеты"],
  ["🎪", "circus tent цирк"],
  ["🤹", "juggling жонглирование"],
  ["🎭", "performing arts театр маски"],
  ["🩰", "ballet shoes балет"],
  ["🎨", "artist palette искусство палитра"],
  ["🎬", "clapper кино"],
  ["🎤", "microphone микрофон караоке"],
  ["🎧", "headphones наушники"],
  ["🎼", "musical score ноты"],
  ["🎹", "piano keyboard пианино"],
  ["🥁", "drum барабан"],
  ["🪘", "long drum барабан"],
  ["🎷", "saxophone саксофон"],
  ["🎺", "trumpet труба"],
  ["🎸", "guitar гитара"],
  ["🪕", "banjo банджо"],
  ["🎻", "violin скрипка"],
  ["🪗", "accordion аккордеон"],
  ["🎲", "dice game кубик игра"],
  ["♟️", "chess pawn шахматы"],
  ["🎯", "direct hit target дартс цель"],
  ["🎳", "bowling боулинг"],
  ["🎮", "video game gamepad игра геймпад"],
  ["🕹️", "joystick джойстик"],
  ["🎰", "slot machine автомат казино"],
  ["🧩", "puzzle piece пазл"],
  ["🃏", "joker card джокер"],
  ["🀄", "mahjong маджонг"],
  ["🎴", "flower cards карты"],
  ["🎨", "palette палитра"],
  ["🧵", "thread нитки"],
  ["🪡", "sewing needle игла"],
  ["🧶", "yarn пряжа"],
  ["🪢", "knot узел"],
];

const TRAVEL: readonly EmojiEntry[] = [
  ["🚗", "car automobile машина авто"],
  ["🚕", "taxi такси"],
  ["🚙", "suv машина"],
  ["🚌", "bus автобус"],
  ["🚎", "trolleybus троллейбус"],
  ["🏎️", "race car гонка"],
  ["🚓", "police car полиция"],
  ["🚑", "ambulance скорая"],
  ["🚒", "fire engine пожарная"],
  ["🚐", "minibus van микроавтобус"],
  ["🛻", "pickup truck пикап"],
  ["🚚", "delivery truck грузовик"],
  ["🚛", "lorry фура грузовик"],
  ["🚜", "tractor трактор"],
  ["🦯", "white cane трость"],
  ["🦽", "manual wheelchair коляска"],
  ["🦼", "motorized wheelchair коляска"],
  ["🛴", "kick scooter самокат"],
  ["🚲", "bicycle велосипед"],
  ["🛵", "motor scooter скутер"],
  ["🏍️", "motorcycle мотоцикл"],
  ["🛺", "auto rickshaw рикша"],
  ["🚨", "police light мигалка сирена"],
  ["🚔", "police car полиция"],
  ["🚍", "bus автобус"],
  ["🚘", "car машина"],
  ["🚖", "taxi такси"],
  ["🚡", "aerial tramway канатка"],
  ["🚠", "mountain cableway канатка"],
  ["🚟", "suspension railway монорельс"],
  ["🚃", "railway car вагон"],
  ["🚋", "tram трамвай"],
  ["🚝", "monorail монорельс"],
  ["🚄", "high speed train поезд"],
  ["🚅", "bullet train поезд"],
  ["🚈", "light rail электричка"],
  ["🚂", "locomotive паровоз поезд"],
  ["🚆", "train поезд"],
  ["🚇", "metro метро"],
  ["🚊", "tram трамвай"],
  ["🚉", "station станция вокзал"],
  ["✈️", "airplane самолёт"],
  ["🛫", "departure plane вылет"],
  ["🛬", "arrival plane прилёт"],
  ["🛩️", "small plane самолёт"],
  ["💺", "seat место кресло"],
  ["🚁", "helicopter вертолёт"],
  ["🚟", "railway"],
  ["🪂", "parachute парашют"],
  ["🛰️", "satellite спутник"],
  ["🚀", "rocket ракета"],
  ["🛸", "ufo нло тарелка"],
  ["🚉", "station"],
  ["⛵", "sailboat парусник яхта"],
  ["🛶", "canoe каноэ лодка"],
  ["🚤", "speedboat катер"],
  ["🛥️", "motor boat катер"],
  ["🛳️", "passenger ship лайнер"],
  ["⛴️", "ferry паром"],
  ["🚢", "ship корабль"],
  ["⚓", "anchor якорь"],
  ["🪝", "hook крюк"],
  ["⛽", "fuel pump заправка бензин"],
  ["🚧", "construction стройка"],
  ["🚦", "traffic light светофор"],
  ["🚥", "horizontal traffic light светофор"],
  ["🚏", "bus stop остановка"],
  ["🗺️", "world map карта"],
  ["🗿", "moai статуя"],
  ["🗽", "statue of liberty свобода"],
  ["🗼", "tokyo tower башня"],
  ["🏰", "castle замок"],
  ["🏯", "japanese castle замок"],
  ["🏟️", "stadium стадион"],
  ["🎡", "ferris wheel колесо обозрения"],
  ["🎢", "roller coaster горки"],
  ["🎠", "carousel карусель"],
  ["⛲", "fountain фонтан"],
  ["⛱️", "beach umbrella зонт пляж"],
  ["🏖️", "beach пляж"],
  ["🏝️", "desert island остров"],
  ["🏜️", "desert пустыня"],
  ["🌋", "volcano вулкан"],
  ["⛰️", "mountain гора"],
  ["🏔️", "snow mountain гора"],
  ["🗻", "fuji фудзи гора"],
  ["🏕️", "camping кемпинг палатка"],
  ["⛺", "tent палатка"],
  ["🏠", "house дом"],
  ["🏡", "house garden дом"],
  ["🏘️", "houses дома"],
  ["🏚️", "derelict house дом"],
  ["🏗️", "construction стройка"],
  ["🏭", "factory завод"],
  ["🏢", "office building офис здание"],
  ["🏬", "department store магазин"],
  ["🏣", "post office почта"],
  ["🏤", "post office почта"],
  ["🏥", "hospital больница"],
  ["🏦", "bank банк"],
  ["🏨", "hotel отель"],
  ["🏪", "convenience store магазин"],
  ["🏫", "school школа"],
  ["🏩", "love hotel отель"],
  ["💒", "wedding chapel свадьба"],
  ["🏛️", "classical building здание"],
  ["⛪", "church церковь"],
  ["🕌", "mosque мечеть"],
  ["🕍", "synagogue синагога"],
  ["🛕", "hindu temple храм"],
  ["🕋", "kaaba кааба"],
  ["⛩️", "shinto shrine ворота"],
  ["🌁", "foggy туман"],
  ["🌃", "starry night ночь город"],
  ["🏙️", "cityscape город"],
  ["🌄", "sunrise mountains рассвет"],
  ["🌅", "sunrise рассвет"],
  ["🌆", "dusk city закат город"],
  ["🌇", "sunset закат"],
  ["🌉", "bridge night мост"],
  ["🌌", "milky way галактика"],
  ["🎇", "fireworks салют"],
  ["🎆", "fireworks фейерверк салют"],
  ["🧭", "compass компас"],
  ["🏞️", "national park природа"],
];

const OBJECTS: readonly EmojiEntry[] = [
  ["⌚", "watch часы наручные"],
  ["📱", "phone smartphone телефон"],
  ["📲", "phone arrow звонок"],
  ["💻", "laptop ноутбук компьютер"],
  ["⌨️", "keyboard клавиатура"],
  ["🖥️", "desktop computer компьютер"],
  ["🖨️", "printer принтер"],
  ["🖱️", "mouse мышка"],
  ["🖲️", "trackball трекбол"],
  ["🕹️", "joystick джойстик"],
  ["🗜️", "clamp зажим"],
  ["💽", "minidisc диск"],
  ["💾", "floppy disk save дискета сохранить"],
  ["💿", "cd диск"],
  ["📀", "dvd диск"],
  ["📼", "videotape кассета"],
  ["📷", "camera фотоаппарат камера"],
  ["📸", "camera flash фото"],
  ["📹", "video camera камера"],
  ["🎥", "movie camera камера кино"],
  ["📽️", "projector проектор"],
  ["🎞️", "film frames плёнка"],
  ["📞", "telephone receiver телефон трубка"],
  ["☎️", "telephone телефон"],
  ["📟", "pager пейджер"],
  ["📠", "fax факс"],
  ["📺", "television телевизор"],
  ["📻", "radio радио"],
  ["🎙️", "studio microphone микрофон"],
  ["🎚️", "level slider ползунок"],
  ["🎛️", "control knobs ручки"],
  ["🧭", "compass компас"],
  ["⏱️", "stopwatch секундомер"],
  ["⏲️", "timer таймер"],
  ["⏰", "alarm clock будильник часы"],
  ["🕰️", "mantelpiece clock часы"],
  ["⌛", "hourglass done песочные часы"],
  ["⏳", "hourglass песочные часы ожидание"],
  ["📡", "satellite antenna антенна"],
  ["🔋", "battery батарея заряд"],
  ["🪫", "low battery батарея"],
  ["🔌", "plug розетка вилка"],
  ["💡", "light bulb idea лампочка идея"],
  ["🔦", "flashlight фонарик"],
  ["🕯️", "candle свеча"],
  ["🪔", "diya lamp лампа"],
  ["🧯", "fire extinguisher огнетушитель"],
  ["🛢️", "oil drum бочка"],
  ["💸", "money wings деньги улетают"],
  ["💵", "dollar доллар деньги"],
  ["💴", "yen йена"],
  ["💶", "euro евро"],
  ["💷", "pound фунт"],
  ["🪙", "coin монета"],
  ["💰", "money bag мешок денег"],
  ["💳", "credit card карта"],
  ["🧾", "receipt чек"],
  ["💎", "gem diamond алмаз бриллиант"],
  ["⚖️", "balance scale весы"],
  ["🪜", "ladder лестница"],
  ["🧰", "toolbox ящик инструментов"],
  ["🪛", "screwdriver отвёртка"],
  ["🔧", "wrench ключ гаечный"],
  ["🔨", "hammer молоток"],
  ["⚒️", "hammer pick инструменты"],
  ["🛠️", "hammer wrench инструменты"],
  ["⛏️", "pick кирка"],
  ["🪚", "saw пила"],
  ["🔩", "nut bolt болт гайка"],
  ["⚙️", "gear шестерёнка настройки"],
  ["🪤", "mouse trap мышеловка"],
  ["🧱", "brick кирпич"],
  ["⛓️", "chains цепи"],
  ["🧲", "magnet магнит"],
  ["🔫", "water pistol пистолет"],
  ["💣", "bomb бомба"],
  ["🧨", "firecracker петарда"],
  ["🪓", "axe топор"],
  ["🔪", "knife нож"],
  ["🗡️", "dagger кинжал"],
  ["⚔️", "crossed swords мечи"],
  ["🛡️", "shield щит"],
  ["🚬", "cigarette сигарета"],
  ["⚰️", "coffin гроб"],
  ["🪦", "headstone надгробие"],
  ["⚱️", "funeral urn урна"],
  ["🏺", "amphora амфора"],
  ["🔮", "crystal ball шар гадание"],
  ["📿", "prayer beads чётки"],
  ["🧿", "nazar amulet амулет"],
  ["🪬", "hamsa амулет"],
  ["💈", "barber pole парикмахерская"],
  ["⚗️", "alembic колба"],
  ["🔭", "telescope телескоп"],
  ["🔬", "microscope микроскоп"],
  ["🕳️", "hole дыра"],
  ["🩹", "bandage пластырь"],
  ["🩺", "stethoscope стетоскоп"],
  ["🩻", "x-ray рентген"],
  ["💊", "pill таблетка"],
  ["💉", "syringe шприц укол"],
  ["🩸", "blood drop кровь"],
  ["🧬", "dna днк"],
  ["🦠", "microbe вирус микроб"],
  ["🧫", "petri dish чашка"],
  ["🧪", "test tube пробирка"],
  ["🌡️", "thermometer термометр"],
  ["🧹", "broom метла"],
  ["🪠", "plunger вантуз"],
  ["🧺", "basket корзина"],
  ["🧻", "toilet paper бумага"],
  ["🚽", "toilet туалет"],
  ["🚰", "potable water вода"],
  ["🚿", "shower душ"],
  ["🛁", "bathtub ванна"],
  ["🛀", "bath ванна"],
  ["🧼", "soap мыло"],
  ["🪥", "toothbrush щётка"],
  ["🪒", "razor бритва"],
  ["🧽", "sponge губка"],
  ["🪣", "bucket ведро"],
  ["🧴", "lotion лосьон"],
  ["🛎️", "bellhop bell звонок"],
  ["🔑", "key ключ"],
  ["🗝️", "old key ключ"],
  ["🚪", "door дверь"],
  ["🪑", "chair стул"],
  ["🛋️", "couch диван"],
  ["🛏️", "bed кровать"],
  ["🧸", "teddy bear мишка игрушка"],
  ["🪆", "nesting dolls матрёшка"],
  ["🖼️", "framed picture картина"],
  ["🪞", "mirror зеркало"],
  ["🪟", "window окно"],
  ["🛍️", "shopping bags покупки"],
  ["🛒", "shopping cart тележка"],
  ["🎁", "gift wrapped present подарок"],
  ["🎈", "balloon шарик"],
  ["🎏", "carp streamer"],
  ["🎀", "ribbon бант лента"],
  ["🪄", "magic wand палочка"],
  ["🎊", "confetti ball конфетти"],
  ["🎉", "party popper праздник тада"],
  ["🎎", "dolls куклы"],
  ["🏮", "red lantern фонарь"],
  ["🎐", "wind chime колокольчик"],
  ["🧧", "red envelope конверт"],
  ["✉️", "envelope конверт письмо"],
  ["📩", "envelope arrow письмо"],
  ["📨", "incoming envelope письмо"],
  ["📧", "email почта"],
  ["💌", "love letter письмо"],
  ["📥", "inbox входящие"],
  ["📤", "outbox исходящие"],
  ["📦", "package посылка коробка"],
  ["🏷️", "label tag бирка"],
  ["📪", "mailbox почтовый ящик"],
  ["📫", "mailbox почта"],
  ["📬", "mailbox mail почта"],
  ["📭", "mailbox empty почта"],
  ["📮", "postbox почта"],
  ["📯", "postal horn рожок"],
  ["📜", "scroll свиток"],
  ["📃", "page документ"],
  ["📄", "page документ"],
  ["📑", "bookmark tabs закладки"],
  ["🧾", "receipt чек"],
  ["📊", "bar chart график"],
  ["📈", "chart up рост график"],
  ["📉", "chart down падение график"],
  ["🗒️", "notepad блокнот"],
  ["🗓️", "calendar календарь"],
  ["📆", "calendar календарь"],
  ["📅", "calendar дата календарь"],
  ["🗑️", "wastebasket корзина мусор"],
  ["📇", "card index картотека"],
  ["🗃️", "card box архив"],
  ["🗳️", "ballot box урна голосование"],
  ["🗄️", "file cabinet шкаф"],
  ["📋", "clipboard буфер"],
  ["📁", "folder папка"],
  ["📂", "open folder папка"],
  ["🗂️", "dividers разделители"],
  ["🗞️", "newspaper газета"],
  ["📰", "newspaper газета новости"],
  ["📓", "notebook тетрадь"],
  ["📔", "notebook decorative тетрадь"],
  ["📒", "ledger журнал"],
  ["📕", "closed book книга"],
  ["📗", "green book книга"],
  ["📘", "blue book книга"],
  ["📙", "orange book книга"],
  ["📚", "books книги"],
  ["📖", "open book книга"],
  ["🔖", "bookmark закладка"],
  ["🧷", "safety pin булавка"],
  ["🔗", "link ссылка"],
  ["📎", "paperclip скрепка"],
  ["🖇️", "paperclips скрепки"],
  ["📐", "triangle ruler линейка"],
  ["📏", "straight ruler линейка"],
  ["🧮", "abacus счёты"],
  ["📌", "pushpin кнопка"],
  ["📍", "round pin метка локация"],
  ["✂️", "scissors ножницы"],
  ["🖊️", "pen ручка"],
  ["🖋️", "fountain pen ручка"],
  ["✒️", "nib перо"],
  ["🖌️", "paintbrush кисть"],
  ["🖍️", "crayon мелок"],
  ["📝", "memo note заметка карандаш"],
  ["✏️", "pencil карандаш"],
  ["🔍", "magnifying glass поиск лупа"],
  ["🔎", "magnifying right поиск лупа"],
  ["🔏", "locked pen замок"],
  ["🔐", "locked key замок"],
  ["🔒", "locked закрыто замок"],
  ["🔓", "unlocked открыто замок"],
  ["🪪", "id card удостоверение"],
  ["🗒️", "spiral notepad блокнот"],
];

const SYMBOLS: readonly EmojiEntry[] = [
  ["❤️", "red heart love любовь"],
  ["🧡", "orange heart сердце"],
  ["💛", "yellow heart сердце"],
  ["💚", "green heart сердце"],
  ["💙", "blue heart сердце"],
  ["💜", "purple heart сердце"],
  ["🖤", "black heart сердце"],
  ["🤍", "white heart сердце"],
  ["🤎", "brown heart сердце"],
  ["💔", "broken heart разбитое"],
  ["❣️", "heart exclamation сердце"],
  ["💕", "two hearts сердечки"],
  ["💞", "revolving hearts сердца"],
  ["💓", "beating heart сердце"],
  ["💗", "growing heart сердце"],
  ["💖", "sparkling heart сердце"],
  ["💘", "heart arrow сердце"],
  ["💝", "heart gift сердце"],
  ["💟", "heart decoration сердце"],
  ["☮️", "peace мир"],
  ["✝️", "cross крест"],
  ["☪️", "star crescent ислам"],
  ["🕉️", "om ом"],
  ["☸️", "dharma wheel колесо"],
  ["✡️", "star david звезда давида"],
  ["🔯", "six pointed star звезда"],
  ["🕎", "menorah менора"],
  ["☯️", "yin yang инь янь"],
  ["☦️", "orthodox cross крест"],
  ["🛐", "place of worship храм"],
  ["⛎", "ophiuchus змееносец"],
  ["♈", "aries овен"],
  ["♉", "taurus телец"],
  ["♊", "gemini близнецы"],
  ["♋", "cancer рак"],
  ["♌", "leo лев"],
  ["♍", "virgo дева"],
  ["♎", "libra весы"],
  ["♏", "scorpio скорпион"],
  ["♐", "sagittarius стрелец"],
  ["♑", "capricorn козерог"],
  ["♒", "aquarius водолей"],
  ["♓", "pisces рыбы"],
  ["🆔", "id идентификатор"],
  ["⚛️", "atom атом"],
  ["🉑", "accept принято"],
  ["☢️", "radioactive радиация"],
  ["☣️", "biohazard биоопасность"],
  ["📴", "phone off без телефона"],
  ["📳", "vibration вибро"],
  ["🈶", "not free платно"],
  ["🈚", "free бесплатно"],
  ["🈸", "application заявка"],
  ["🈺", "open работает"],
  ["🈷️", "monthly месяц"],
  ["✴️", "eight pointed star звезда"],
  ["🆚", "vs против"],
  ["💮", "white flower цветок"],
  ["🉐", "bargain выгода"],
  ["㊙️", "secret секрет"],
  ["㊗️", "congratulations поздравление"],
  ["🈴", "passing grade зачёт"],
  ["🈵", "full заполнено"],
  ["🈲", "prohibited запрет"],
  ["🅰️", "a button группа а"],
  ["🅱️", "b button группа б"],
  ["🆎", "ab button"],
  ["🆑", "cl button"],
  ["🅾️", "o button"],
  ["🆘", "sos помощь"],
  ["❌", "cross mark no нет крестик"],
  ["⭕", "circle red нолик"],
  ["🛑", "stop sign стоп"],
  ["⛔", "no entry нельзя"],
  ["📛", "name badge бейдж"],
  ["🚫", "prohibited запрещено"],
  ["💯", "hundred сто"],
  ["💢", "anger злость"],
  ["♨️", "hot springs горячий источник"],
  ["🚷", "no pedestrians"],
  ["🚯", "no littering не мусорить"],
  ["🚳", "no bicycles"],
  ["🚱", "non potable water"],
  ["🔞", "18 plus restriction"],
  ["📵", "no phones"],
  ["🚭", "no smoking не курить"],
  ["❗", "exclamation восклицание"],
  ["❕", "white exclamation восклицание"],
  ["❓", "question вопрос"],
  ["❔", "white question вопрос"],
  ["‼️", "double exclamation восклицание"],
  ["⁉️", "exclamation question вопрос"],
  ["🔅", "dim low brightness яркость"],
  ["🔆", "bright brightness яркость"],
  ["〽️", "part alternation"],
  ["⚠️", "warning предупреждение внимание"],
  ["🚸", "children crossing дети"],
  ["🔱", "trident трезубец"],
  ["⚜️", "fleur de lis лилия"],
  ["🔰", "beginner новичок"],
  ["♻️", "recycle переработка"],
  ["✅", "check mark green галочка да"],
  ["☑️", "checkbox галочка"],
  ["✔️", "check mark галочка"],
  ["🔟", "keycap 10"],
  ["🔢", "numbers цифры"],
  ["#️⃣", "hash решётка"],
  ["*️⃣", "asterisk звёздочка"],
  ["0️⃣", "zero ноль"],
  ["1️⃣", "one один"],
  ["2️⃣", "two два"],
  ["3️⃣", "three три"],
  ["4️⃣", "four четыре"],
  ["5️⃣", "five пять"],
  ["6️⃣", "six шесть"],
  ["7️⃣", "seven семь"],
  ["8️⃣", "eight восемь"],
  ["9️⃣", "nine девять"],
  ["🔣", "symbols символы"],
  ["➡️", "right arrow стрелка вправо"],
  ["⬅️", "left arrow стрелка влево"],
  ["⬆️", "up arrow стрелка вверх"],
  ["⬇️", "down arrow стрелка вниз"],
  ["↗️", "up right arrow стрелка"],
  ["↘️", "down right arrow стрелка"],
  ["↙️", "down left arrow стрелка"],
  ["↖️", "up left arrow стрелка"],
  ["↕️", "up down arrow стрелка"],
  ["↔️", "left right arrow стрелка"],
  ["↩️", "right hook arrow назад"],
  ["↪️", "left hook arrow вперёд"],
  ["⤴️", "right curve arrow стрелка"],
  ["⤵️", "down curve arrow стрелка"],
  ["🔃", "clockwise arrows обновить"],
  ["🔄", "counterclockwise обновить"],
  ["🔙", "back назад"],
  ["🔚", "end конец"],
  ["🔛", "on включено"],
  ["🔜", "soon скоро"],
  ["🔝", "top верх"],
  ["🔀", "shuffle перемешать"],
  ["🔁", "repeat повтор"],
  ["🔂", "repeat one повтор"],
  ["▶️", "play воспроизвести"],
  ["⏸️", "pause пауза"],
  ["⏯️", "play pause"],
  ["⏹️", "stop стоп"],
  ["⏺️", "record запись"],
  ["⏭️", "next track следующий"],
  ["⏮️", "previous track предыдущий"],
  ["⏩", "fast forward перемотка"],
  ["⏪", "rewind перемотка"],
  ["⏫", "fast up вверх"],
  ["⏬", "fast down вниз"],
  ["◀️", "reverse назад"],
  ["🔼", "up button вверх"],
  ["🔽", "down button вниз"],
  ["🎦", "cinema кино"],
  ["🔅", "dim"],
  ["📶", "signal сигнал сеть"],
  ["📳", "vibrate вибро"],
  ["♾️", "infinity бесконечность"],
  ["➕", "plus плюс"],
  ["➖", "minus минус"],
  ["➗", "divide делить"],
  ["✖️", "multiply умножить"],
  ["🟰", "equals равно"],
  ["💲", "dollar sign доллар"],
  ["💱", "currency exchange обмен валют"],
  ["™️", "trademark тм"],
  ["©️", "copyright копирайт"],
  ["®️", "registered зарегистрировано"],
  ["〰️", "wavy dash волна"],
  ["➰", "curl loop"],
  ["➿", "double loop"],
  ["🔚", "end"],
  ["🔘", "radio button кнопка"],
  ["⚪", "white circle белый круг"],
  ["⚫", "black circle чёрный круг"],
  ["🔴", "red circle красный круг"],
  ["🟠", "orange circle оранжевый круг"],
  ["🟡", "yellow circle жёлтый круг"],
  ["🟢", "green circle зелёный круг"],
  ["🔵", "blue circle синий круг"],
  ["🟣", "purple circle фиолетовый круг"],
  ["🟤", "brown circle коричневый круг"],
  ["🔺", "red triangle up треугольник"],
  ["🔻", "red triangle down треугольник"],
  ["🔸", "small orange diamond ромб"],
  ["🔹", "small blue diamond ромб"],
  ["🔶", "large orange diamond ромб"],
  ["🔷", "large blue diamond ромб"],
  ["🔳", "white square квадрат"],
  ["🔲", "black square квадрат"],
  ["▪️", "black small square квадрат"],
  ["▫️", "white small square квадрат"],
  ["◾", "black medium square квадрат"],
  ["◽", "white medium square квадрат"],
  ["◼️", "black medium square"],
  ["◻️", "white medium square"],
  ["🟥", "red square красный квадрат"],
  ["🟧", "orange square оранжевый квадрат"],
  ["🟨", "yellow square жёлтый квадрат"],
  ["🟩", "green square зелёный квадрат"],
  ["🟦", "blue square синий квадрат"],
  ["🟪", "purple square фиолетовый квадрат"],
  ["🟫", "brown square коричневый квадрат"],
  ["⬛", "black large square квадрат"],
  ["⬜", "white large square квадрат"],
  ["🔈", "speaker low громкость"],
  ["🔇", "muted без звука"],
  ["🔉", "speaker medium звук"],
  ["🔊", "speaker loud звук громко"],
  ["🔔", "bell колокольчик уведомление"],
  ["🔕", "bell off без звука"],
  ["📣", "megaphone рупор"],
  ["📢", "loudspeaker громкоговоритель"],
  ["💬", "speech balloon реплика"],
  ["💭", "thought мысль"],
  ["🗯️", "anger bubble ярость"],
  ["♠️", "spades пики"],
  ["♣️", "clubs трефы"],
  ["♥️", "hearts червы"],
  ["♦️", "diamonds бубны"],
  ["🃏", "joker джокер"],
  ["🎴", "flower card карты"],
  ["🀄", "mahjong маджонг"],
  ["🕐", "clock 1 час"],
  ["🕑", "clock 2 часа"],
  ["🕒", "clock 3 часа"],
  ["🕓", "clock 4 часа"],
  ["🕔", "clock 5 часов"],
  ["🕕", "clock 6 часов"],
  ["⏰", "alarm будильник"],
  ["🌐", "globe meridians сеть глобус"],
  ["♿", "wheelchair доступность"],
  ["🚹", "men toilet туалет м"],
  ["🚺", "women toilet туалет ж"],
  ["🚼", "baby symbol ребёнок"],
  ["🚻", "restroom туалет"],
  ["🅿️", "parking парковка"],
  ["🆒", "cool круто"],
  ["🆕", "new новое"],
  ["🆓", "free бесплатно"],
  ["🆗", "ok окей"],
  ["🆙", "up вверх"],
  ["🈯", "reserved зарезервировано"],
  ["💠", "diamond dot ромб"],
  ["Ⓜ️", "circled m метро"],
  ["🔤", "abc буквы"],
  ["🔡", "lowercase буквы"],
  ["🔠", "uppercase буквы"],
];

const FLAGS: readonly EmojiEntry[] = [
  ["🏁", "checkered flag финиш"],
  ["🚩", "triangular flag флаг"],
  ["🎌", "crossed flags флаги"],
  ["🏴", "black flag чёрный флаг"],
  ["🏳️", "white flag белый флаг"],
  ["🏳️‍🌈", "rainbow flag радужный лгбт"],
  ["🏳️‍⚧️", "transgender flag"],
  ["🏴‍☠️", "pirate flag пиратский"],
  ["🇷🇺", "russia россия флаг"],
  ["🇺🇦", "ukraine украина флаг"],
  ["🇧🇾", "belarus беларусь флаг"],
  ["🇰🇿", "kazakhstan казахстан флаг"],
  ["🇺🇸", "usa america сша флаг"],
  ["🇬🇧", "uk britain великобритания флаг"],
  ["🇩🇪", "germany германия флаг"],
  ["🇫🇷", "france франция флаг"],
  ["🇮🇹", "italy италия флаг"],
  ["🇪🇸", "spain испания флаг"],
  ["🇵🇹", "portugal португалия флаг"],
  ["🇳🇱", "netherlands нидерланды флаг"],
  ["🇧🇪", "belgium бельгия флаг"],
  ["🇨🇭", "switzerland швейцария флаг"],
  ["🇦🇹", "austria австрия флаг"],
  ["🇵🇱", "poland польша флаг"],
  ["🇨🇿", "czech чехия флаг"],
  ["🇸🇰", "slovakia словакия флаг"],
  ["🇭🇺", "hungary венгрия флаг"],
  ["🇷🇴", "romania румыния флаг"],
  ["🇧🇬", "bulgaria болгария флаг"],
  ["🇬🇷", "greece греция флаг"],
  ["🇹🇷", "turkey турция флаг"],
  ["🇸🇪", "sweden швеция флаг"],
  ["🇳🇴", "norway норвегия флаг"],
  ["🇩🇰", "denmark дания флаг"],
  ["🇫🇮", "finland финляндия флаг"],
  ["🇮🇪", "ireland ирландия флаг"],
  ["🇮🇸", "iceland исландия флаг"],
  ["🇪🇪", "estonia эстония флаг"],
  ["🇱🇻", "latvia латвия флаг"],
  ["🇱🇹", "lithuania литва флаг"],
  ["🇬🇪", "georgia грузия флаг"],
  ["🇦🇲", "armenia армения флаг"],
  ["🇦🇿", "azerbaijan азербайджан флаг"],
  ["🇺🇿", "uzbekistan узбекистан флаг"],
  ["🇰🇬", "kyrgyzstan киргизия флаг"],
  ["🇹🇯", "tajikistan таджикистан флаг"],
  ["🇹🇲", "turkmenistan туркмения флаг"],
  ["🇲🇩", "moldova молдова флаг"],
  ["🇨🇳", "china китай флаг"],
  ["🇯🇵", "japan япония флаг"],
  ["🇰🇷", "korea корея флаг"],
  ["🇮🇳", "india индия флаг"],
  ["🇧🇷", "brazil бразилия флаг"],
  ["🇨🇦", "canada канада флаг"],
  ["🇲🇽", "mexico мексика флаг"],
  ["🇦🇷", "argentina аргентина флаг"],
  ["🇦🇺", "australia австралия флаг"],
  ["🇳🇿", "new zealand новая зеландия флаг"],
  ["🇿🇦", "south africa юар флаг"],
  ["🇪🇬", "egypt египет флаг"],
  ["🇦🇪", "uae эмираты флаг"],
  ["🇸🇦", "saudi arabia саудовская флаг"],
  ["🇮🇱", "israel израиль флаг"],
  ["🇹🇭", "thailand таиланд флаг"],
  ["🇻🇳", "vietnam вьетнам флаг"],
  ["🇮🇩", "indonesia индонезия флаг"],
  ["🇵🇭", "philippines филиппины флаг"],
  ["🇸🇬", "singapore сингапур флаг"],
  ["🇲🇾", "malaysia малайзия флаг"],
];

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  { id: "smileys", label: "Смайлы и эмоции", icon: "😀", entries: SMILEYS },
  { id: "people", label: "Люди и жесты", icon: "👋", entries: PEOPLE },
  { id: "animals", label: "Животные и природа", icon: "🐻", entries: ANIMALS },
  { id: "food", label: "Еда и напитки", icon: "🍔", entries: FOOD },
  { id: "activities", label: "Активность", icon: "⚽", entries: ACTIVITIES },
  { id: "travel", label: "Путешествия и места", icon: "✈️", entries: TRAVEL },
  { id: "objects", label: "Предметы", icon: "💡", entries: OBJECTS },
  { id: "symbols", label: "Символы", icon: "❤️", entries: SYMBOLS },
  { id: "flags", label: "Флаги", icon: "🏁", entries: FLAGS },
];

/** Default emoji shown in the "frequently used" section before any history. */
export const DEFAULT_RECENT_EMOJIS: readonly string[] = [
  "👍", "❤️", "😂", "🔥", "🎉", "😍", "😢", "🙏",
  "👏", "💯", "😮", "🤔", "✅", "👀", "😅", "🥰",
];

const RECENT_KEY = "lentik:emoji:recent";
const RECENT_CAP = 32;

export function getRecentEmojis(): string[] {
  if (typeof window === "undefined") return [...DEFAULT_RECENT_EMOJIS];
  try {
    const raw = window.localStorage.getItem(RECENT_KEY);
    if (!raw) return [...DEFAULT_RECENT_EMOJIS];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [...DEFAULT_RECENT_EMOJIS];
    const list = parsed.filter((x): x is string => typeof x === "string");
    return list.length ? list.slice(0, RECENT_CAP) : [...DEFAULT_RECENT_EMOJIS];
  } catch {
    return [...DEFAULT_RECENT_EMOJIS];
  }
}

export function pushRecentEmoji(emoji: string): string[] {
  const current = getRecentEmojis();
  const next = [emoji, ...current.filter((e) => e !== emoji)].slice(0, RECENT_CAP);
  if (typeof window !== "undefined") {
    try {
      window.localStorage.setItem(RECENT_KEY, JSON.stringify(next));
    } catch {
      /* storage full / unavailable — non-fatal */
    }
  }
  return next;
}

// Flat lookup for search: every entry across content categories, de-duplicated
// by emoji (first keyword wins for the human-readable name).
const ALL_ENTRIES: readonly EmojiEntry[] = (() => {
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const entry of cat.entries) {
      if (seen.has(entry[0])) continue;
      seen.add(entry[0]);
      out.push(entry);
    }
  }
  return out;
})();

/** Human-readable primary name for an emoji (first keyword token group). */
export function emojiName(emoji: string): string {
  const found = ALL_ENTRIES.find((e) => e[0] === emoji);
  if (!found) return emoji;
  return found[1].split(" ").slice(0, 3).join(" ");
}

/**
 * Search emojis by keyword. Every whitespace-separated term in the query must
 * appear as a substring of the entry's keyword string (AND semantics). Matching
 * is case-insensitive; supports both Latin and Cyrillic terms.
 */
export function searchEmojis(query: string, limit = 64): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  for (const [emoji, keywords] of ALL_ENTRIES) {
    if (terms.every((t) => keywords.includes(t) || emoji === t)) {
      out.push(emoji);
      if (out.length >= limit) break;
    }
  }
  return out;
}
